#!/usr/bin/env python3
"""Regenerate the per-extension pages, and list them in the navigation.

Each extension has one body, in snippets/extensions/<slug>.mdx, and one thin
page per slot that imports it. This script writes those pages and rewrites the
Extensions group in every docs.json navigation that has one, so adding an
extension needs no hand edit of docs.json. Run it after adding an extension,
renaming a slot, or changing a See also list.

It also refuses to run when the catalog in snippets/extensions-en.mdx and the
bodies in snippets/extensions/ name different sets of extensions, because that
mismatch otherwise ships as a catalog entry with no page behind it.

Two Mintlify constraints shape this layout. Both were measured, and both look
like bugs in our own pages when they bite:

1. An .mdx snippet does NOT receive properties. Passing `slot="..."` into one
   and reading `{props.slot}` inside compiles, renders, and yields an empty
   string, so every link built that way becomes href="". Properties work only
   for .jsx snippets that export a function. This is why a slot-specific link
   cannot live in the shared body.

2. A relative link (../install) resolves correctly in the rendered page, but
   `mint broken-links` reads the snippet on its own, finds no such page, and
   exits 1. That check gates CI, so relative links are out too.

What is left is an absolute link written per slot, which is what this script
generates. The See also list therefore lives in the generated page rather than
in the shared body.

Usage:  python3 scripts/gen-extension-pages.py          # from the repo root
"""

import json
import os
import re
import sys

SLOTS = ["mysql-8.4/stable", "mysql-8.4/dev", "mysql-9.7/stable", "mysql-9.7/dev"]
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "scripts", "extension-pages.json")
DOCS_JSON = os.path.join(REPO, "docs.json")
CATALOG = os.path.join(REPO, "snippets", "extensions-en.mdx")

GENERATED_NOTE = (
    "{/* Generated by scripts/gen-extension-pages.py. Edit the body in\n"
    "    snippets/extensions/<slug>.mdx, and the title, description and\n"
    "    See also list in scripts/extension-pages.json, then re-run it.\n"
    "    See also is here, not in the snippet, because a snippet cannot take\n"
    "    a property and a relative link fails mint broken-links. */}"
)


def component_name(slug):
    return "".join(part.capitalize() for part in slug.split("-")) + "Page"


def resolve(item, slot):
    """Turn the slot-relative forms in the data file into absolute links."""
    item = re.sub(r"\]\(\.\./([a-z0-9-]+)\)", rf"](/{slot}/\1)", item)
    item = re.sub(r"\]\((vsql-[a-z0-9-]+)\)", rf"](/{slot}/extensions/\1)", item)
    return item


def catalog_slugs():
    """The extensions the catalog page lists, as page slugs."""
    heads = re.findall(r"^### (\S+)\s*$", open(CATALOG).read(), re.M)
    return {h.replace("_", "-") for h in heads}


def check_catalog(slugs):
    """Refuse to run when the catalog and the bodies disagree."""
    listed = catalog_slugs()
    missing_page = sorted(listed - set(slugs))
    missing_entry = sorted(set(slugs) - listed)
    if not missing_page and not missing_entry:
        return
    for slug in missing_page:
        print(f"catalog lists {slug} but snippets/extensions/{slug}.mdx does not exist")
    for slug in missing_entry:
        print(f"snippets/extensions/{slug}.mdx exists but the catalog does not list it")
    sys.exit("catalog and pages disagree; fix one of them and re-run")


def update_navigation(slugs):
    """Rewrite every Extensions group in docs.json to list the pages."""
    docs = json.load(open(DOCS_JSON))
    groups = []

    def walk(node, slot):
        if isinstance(node, dict):
            if node.get("group") == "Extensions" and isinstance(node.get("pages"), list):
                groups.append(node)
            for value in node.values():
                walk(value, slot)
        elif isinstance(node, list):
            for value in node:
                walk(value, slot)

    walk(docs["navigation"], None)
    for group in groups:
        # every page in a group shares one slot; take it from the group root
        root = group.get("root") or group["pages"][0]
        slot = "/".join(root.split("/")[:-1]).lstrip("/")
        if slot.split("/")[0] in ("ja", "ko", "zh", "pt-BR"):
            slot = "/".join(slot.split("/")[1:])  # locale navs list the English pages
        group["pages"] = [f"{slot}/extensions/{s}" for s in slugs]

    json.dump(docs, open(DOCS_JSON, "w"), indent=2, ensure_ascii=False)
    open(DOCS_JSON, "a").write("\n")
    return len(groups)


def main():
    data = json.load(open(DATA))
    check_catalog(sorted(data))
    written = 0
    for slug, page in sorted(data.items()):
        body = f"snippets/extensions/{slug}.mdx"
        if not os.path.exists(body):
            sys.exit(f"missing body: {body}")
        comp = component_name(slug)
        for slot in SLOTS:
            os.makedirs(f"{slot}/extensions", exist_ok=True)
            see = "\n".join(resolve(i, slot) for i in page["see_also"])
            open(f"{slot}/extensions/{slug}.mdx", "w").write(
                "---\n"
                f'title: "{page["title"]}"\n'
                f'sidebarTitle: "{page["sidebar_title"]}"\n'
                f'description: "{page["description"]}"\n'
                f'keywords: "{page["keywords"]}"\n'
                "audience: villagesql-user\n"
                "---\n\n"
                + GENERATED_NOTE.replace("<slug>", slug)
                + "\n\n"
                f'import {comp} from "/{body}";\n\n'
                f"<{comp} />\n\n"
                "## See also\n\n" + see + "\n"
            )
            written += 1
    navs = update_navigation(sorted(data))
    print(f"wrote {written} pages for {len(data)} extensions across {len(SLOTS)} slots")
    print(f"listed them in {navs} navigation groups")


if __name__ == "__main__":
    main()
