#!/usr/bin/env python3
"""Regenerate the per-extension pages in every live version slot.

Each extension has one body, in snippets/extensions/<slug>.mdx, and one thin
page per slot that imports it. Run this after adding an extension, renaming a
slot, or changing a See also list.

Two Mintlify constraints shape this layout. Both were measured, and both look
like bugs in our own pages when they bite:

1. An .mdx snippet does NOT receive properties. Passing `slot="..."` into one
   and reading `{props.slot}` inside compiles, renders, and yields an empty
   string, so every link built that way becomes href="". Properties work only
   for .jsx snippets that export a function. This is why a slot-specific link
   cannot live in the shared body.

2. A relative link (../install) resolves correctly in the rendered page, but
   `mint broken-links` reads the snippet on its own, finds no such page, and
   exits 1. That check gates CI, so relative links are out too.

What is left is an absolute link written per slot, which is what this script
generates. The See also list therefore lives in the generated page rather than
in the shared body.

Usage:  python3 scripts/gen-extension-pages.py          # from the repo root
"""

import json
import os
import re
import sys

SLOTS = ["mysql-8.4/stable", "mysql-8.4/dev", "mysql-9.7/stable", "mysql-9.7/dev"]
DATA = os.path.join(os.path.dirname(__file__), "extension-pages.json")

GENERATED_NOTE = (
    "{/* Generated by scripts/gen-extension-pages.py. Edit the body in\n"
    "    snippets/extensions/<slug>.mdx, and the title, description and\n"
    "    See also list in scripts/extension-pages.json, then re-run it.\n"
    "    See also is here, not in the snippet, because a snippet cannot take\n"
    "    a property and a relative link fails mint broken-links. */}"
)


def component_name(slug):
    return "".join(part.capitalize() for part in slug.split("-")) + "Page"


def resolve(item, slot):
    """Turn the slot-relative forms in the data file into absolute links."""
    item = re.sub(r"\]\(\.\./([a-z0-9-]+)\)", rf"](/{slot}/\1)", item)
    item = re.sub(r"\]\((vsql-[a-z0-9-]+)\)", rf"](/{slot}/extensions/\1)", item)
    return item


def main():
    data = json.load(open(DATA))
    written = 0
    for slug, page in sorted(data.items()):
        body = f"snippets/extensions/{slug}.mdx"
        if not os.path.exists(body):
            sys.exit(f"missing body: {body}")
        comp = component_name(slug)
        for slot in SLOTS:
            os.makedirs(f"{slot}/extensions", exist_ok=True)
            see = "\n".join(resolve(i, slot) for i in page["see_also"])
            open(f"{slot}/extensions/{slug}.mdx", "w").write(
                "---\n"
                f'title: "{page["title"]}"\n'
                f'sidebarTitle: "{page["sidebar_title"]}"\n'
                f'description: "{page["description"]}"\n'
                f'keywords: "{page["keywords"]}"\n'
                "audience: villagesql-user\n"
                "---\n\n"
                + GENERATED_NOTE.replace("<slug>", slug)
                + "\n\n"
                f'import {comp} from "/{body}";\n\n'
                f"<{comp} />\n\n"
                "## See also\n\n" + see + "\n"
            )
            written += 1
    print(f"wrote {written} pages for {len(data)} extensions across {len(SLOTS)} slots")


if __name__ == "__main__":
    main()
